import type { Metadata } from "next";
import type { PropsWithChildren } from "react";

import { Geist, Geist_Mono } from "next/font/google";
import { getLocale } from "next-intl/server";

import "~/common/ui/style/global.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Fit Journal",
  description: "Generated by create next app"
};

const RootLayout = async ({
  children
}: Readonly<PropsWithChildren>) => {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
