import type { Metadata } from "next";
import type { PropsWithChildren } from "react";

import Script from "next/script";
import { getLocale } from "next-intl/server";

import { PostHogProvider } from "~/app/provider";
import { fontConfig } from "~/common/lib/config/font.config";

import "~/common/ui/style/global.scss";

export const metadata: Metadata = {
  title: "Fit Journal",
  description: "Generated by create next app",

  viewport: {
    width: "device-width",
    initialScale: 1.0,
    maximumScale: 1.0,
    minimumScale: 1.0,
    userScalable: false
  }
};

const RootLayout = async ({
  children
}: Readonly<PropsWithChildren>) => {
  const locale = await getLocale();

  return (
    <html lang={locale} className={fontConfig}>
      <head>
        {/* Google Tag Manager */}
        <Script id="gtm-script" strategy="afterInteractive">
          {`
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-K946HZNT');
          `}
        </Script>
        {/* End Google Tag Manager */}

        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-36486VE5T0"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-36486VE5T0');
          `}
        </Script>
        {/* End Google Analytics */}
      </head>
      <body>
        {/* Google Tag Manager (noscript) */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-K946HZNT"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          ></iframe>
        </noscript>
        {/* End Google Tag Manager (noscript) */}

        <PostHogProvider>
          {children}
        </PostHogProvider>
      </body>
    </html>
  );
};

export default RootLayout;
