import type { Metadata } from "next";
import type { PropsWithChildren } from "react";

import { getLocale } from "next-intl/server";

import { fontConfig } from "~/common/lib/config/font.config";

import "~/common/ui/style/global.scss";

export const metadata: Metadata = {
  title: "Fit Journal",
  description: "Generated by create next app",

  viewport: {
    width: "device-width",
    initialScale: 1.0,
    maximumScale: 1.0,
    minimumScale: 1.0,
    userScalable: false
  }
};

const RootLayout = async ({
  children
}: Readonly<PropsWithChildren>) => {
  const locale = await getLocale();

  return (
    <html lang={locale} className={fontConfig}>
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
